DROP TABLE IF EXISTS repayment; CREATE TABLE repayment (repay_id BIGINT NOT NULL, repay_amount BIGINT NULL, repay_date DATETIME NULL, loan_id VARCHAR(256) NOT NULL, PRIMARY KEY (repay_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS guarantee; CREATE TABLE guarantee (guarantee_id BIGINT NOT NULL, guarantee_name VARCHAR(256) NULL, guarantee_type VARCHAR(64) NULL, guarantee_value BIGINT NULL, guarantee_file BLOB NULL, loan_id VARCHAR(256) NOT NULL, PRIMARY KEY (guarantee_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Item; CREATE TABLE Item (Item_id BIGINT NOT NULL, bank_id BIGINT NOT NULL, Item_name VARCHAR(256) NULL, Interest_rate DOUBLE NULL, PRIMARY KEY (Item_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Bank; CREATE TABLE Bank (bank_id BIGINT NOT NULL, balance BIGINT NULL, PRIMARY KEY (bank_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Transaction; CREATE TABLE Transaction (t_id INT NOT NULL, account_id VARCHAR(256) NOT NULL, t_type VARCHAR(64) NULL, amount BIGINT NULL, t_date DATE NULL, description VARCHAR(256) NULL, PRIMARY KEY (t_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Deposit; CREATE TABLE Deposit (`Key` VARCHAR(255) NOT NULL, Item_id BIGINT NOT NULL, account_id VARCHAR(256) NOT NULL, amount BIGINT NULL, Field2 DATETIME NULL, valid_date TINYINT(1) NULL, PRIMARY KEY (`Key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Client; CREATE TABLE Client (cl_id INT NOT NULL, cl_resi_num VARCHAR(256) NOT NULL, cl_name VARCHAR(256) NULL, cl_number CHAR(13) NULL, cl_birthday DATE NULL, cl_address VARCHAR(256) NULL, cl_email VARCHAR(256) NULL, cl_job VARCHAR(256) NULL, PRIMARY KEY (cl_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Card; CREATE TABLE Card (card_num VARCHAR(256) NOT NULL, card_cl_name VARCHAR(256) NULL, card_valid_date DATE NULL, card_cvc INT NULL, card_limit BIGINT NULL, account_id VARCHAR(256) NOT NULL, Item_id BIGINT NOT NULL, PRIMARY KEY (card_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS loan; CREATE TABLE loan (loan_id VARCHAR(256) NOT NULL, loan_amount BIGINT NULL, loan_status VARCHAR(64) NULL, loan_date DATETIME NULL, guarantee_valid TINYINT(1) NULL, account_id VARCHAR(255) NOT NULL, Item_id BIGINT NOT NULL, PRIMARY KEY (loan_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS Account; CREATE TABLE Account (account_id VARCHAR(256) NOT NULL, account_number VARCHAR(30) NULL, account_type VARCHAR(64) NULL, date DATE NULL, balance BIGINT NULL, cl_id INT NOT NULL, PRIMARY KEY (account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;