CREATE TABLE IF NOT EXISTS repayment (repay_id BIGINT NOT NULL AUTO_INCREMENT, repay_amount BIGINT NULL, repay_date DATETIME NULL, loan_id VARCHAR(255) NOT NULL, cl_number CHAR(13) NULL, PRIMARY KEY (repay_id));

CREATE TABLE IF NOT EXISTS guarantee (guarantee_id BIGINT NOT NULL AUTO_INCREMENT, guarantee_name VARCHAR(255) NULL, guarantee_type ENUM('TYPE1','TYPE2') NULL, guarantee_value BIGINT NULL, guarantee_file BLOB NULL, loan_id VARCHAR(255) NOT NULL, cl_number CHAR(13) NULL, PRIMARY KEY (guarantee_id));

CREATE TABLE IF NOT EXISTS Item (Item_id BIGINT NOT NULL AUTO_INCREMENT, bank_id BIGINT NOT NULL, Item_name VARCHAR(255) NULL, Interest_rate DOUBLE NULL, PRIMARY KEY (Item_id));

CREATE TABLE IF NOT EXISTS Bank (bank_id BIGINT NOT NULL AUTO_INCREMENT, balance BIGINT NULL, PRIMARY KEY (bank_id));

CREATE TABLE IF NOT EXISTS Transaction (t_id INT NOT NULL AUTO_INCREMENT, account_id VARCHAR(256) NOT NULL, t_type ENUM('DEPOSIT','WITHDRAW') NULL, amount BIGINT NULL, t_date DATE NULL, description VARCHAR(256) NULL, PRIMARY KEY (t_id));

CREATE TABLE IF NOT EXISTS Deposit (deposit_key VARCHAR(255) NOT NULL, Item_id BIGINT NOT NULL, account_id VARCHAR(256) NOT NULL, amount BIGINT NULL, maturityDate DATETIME NULL, valid BOOLEAN NULL, PRIMARY KEY (deposit_key));

CREATE TABLE IF NOT EXISTS Client (cl_id INT NOT NULL AUTO_INCREMENT, cl_userId VARCHAR(16) NULL, cl_userPw VARCHAR(256) NULL, cl_resi_num VARCHAR(255) NOT NULL, cl_name VARCHAR(255) NULL, cl_number CHAR(13) NULL, cl_birthday DATE NULL, cl_address VARCHAR(255) NULL, cl_email VARCHAR(255) NULL, cl_job VARCHAR(255) NULL, PRIMARY KEY (cl_id));

CREATE TABLE IF NOT EXISTS Card (card_num VARCHAR(255) NOT NULL, card_cl_name VARCHAR(255) NULL, card_valid_date DATE NULL, card_cvc INT NULL, card_limit BIGINT NULL, account_id VARCHAR(256) NOT NULL, Item_id BIGINT NOT NULL, PRIMARY KEY (card_num));

CREATE TABLE IF NOT EXISTS loan (loan_id VARCHAR(255) NOT NULL, loan_amount BIGINT NULL, loan_status ENUM('ONGOING','PAID','DEFAULT') NULL, loan_date DATETIME NULL, guarantee_valid BOOLEAN NULL, account_id VARCHAR(255) NOT NULL, Item_id BIGINT NOT NULL, cl_number CHAR(13) NULL, PRIMARY KEY (loan_id));

CREATE TABLE IF NOT EXISTS Account (account_id VARCHAR(256) NOT NULL, account_number VARCHAR(30) NULL, account_type ENUM('SAVING','CHECKING','LOAN') NULL, date DATE NULL, balance BIGINT NULL, cl_id INT NOT NULL, cl_job VARCHAR(255) NULL, PRIMARY KEY (account_id));